quizbook/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from quizbook import views
from quizbook_app import views as quizbook_app_views
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', quizbook_app_views.home, name='home'),
    url(r'^signup/$', quizbook_app_views.signup, name='signup'),
    url(r'^login$', quizbook_app_views.login_view, name='login'),
    url(r'^logout/$', quizbook_app_views.logout_view, name='logout'),
    url(r'^courses/', include('quizbook_app.urls', namespace="courses")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^get_solution/$', quizbook_app_views.get_solution, name='get_solution'),
    url(r'^about/$', views.get_about, name='about'),
    url(r'^add_solution/*$', quizbook_app_views.add_solution_ajax),

)

quizbook_app/urls.py
from django.conf.urls import patterns, url
from quizbook_app import views
from django.contrib import admin
admin.autodiscover()
from quizbook_app import views as quizbook_app_views

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
    url(r'^print_courses/$', views.text_courses, name='text_courses'),
    url(r'^latex_courses/$', views.latex_courses, name='latex_courses'),
    url(r'^new_course/$', views.new_course_page, name='new_course_page'),
    url(r'^new_course/process$', views.new_course_process, name='new_course_process'),

    url(r'^(?P<course_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<course_id>\d+)/practice/$', views.practice_question, name='practise'),
    # url(r'^(?P<course_id>\d+)/random/$', views.random_quiz, name='random_quiz'),
    url(r'^(?P<course_id>\d+)/enroll/$', views.enroll_user_in_course, name='enroll'),
    url(r'^(?P<course_id>\d+)/drop/$', views.drop_user_from_course, name='drop'),
    url(r'^(?P<course_id>\d+)/delete/$', views.delete_course, name='delete_course'),
    url(r'^(?P<course_id>\d+)/new_quiz/$', views.new_quiz_page, name='new_quiz_page'),
    url(r'^(?P<course_id>\d+)/new_quiz/process/$', views.new_quiz_process, name='new_quiz_process'),

    url(r'^(?P<course_id>\d+)/quiz/$', views.quiz, name='quiz'),
    url(r'^\d+/quiz(?P<quiz_id>\d+)/answer/$', views.practice_answer, name='answer'),

    url(r'^(?P<course_id>\d+)/(?P<quiz_id>\d+)/$', views.quiz_page, name='quiz_page'),
    url(r'^(?P<course_id>\d+)/(?P<quiz_id>\d+)/delete/$', views.delete_quiz, name='delete_quiz'),
    url(r'^(?P<course_id>\d+)/(?P<quiz_id>\d+)/update/$', views.update_quiz, name='update_quiz'),
    url(r'^(?P<course_id>\d+)/(?P<quiz_id>\d+)/edit/$', views.edit_quiz_page, name='edit_quiz'),
    url(r'^(?P<course_id>\d+)/(?P<quiz_id>\d+)/edit/process/$', views.edit_quiz_process, name='edit_quiz_process'),
    url(r'^(?P<course_id>\d+)/(?P<quiz_id>\d+)/add_solution/$', views.add_solution, name='add_solution'),
    url(r'^(?P<course_id>\d+)/(?P<quiz_id>\d+)/add_solution/process/$', views.process_add_solution, name='process_add_solution'),
    url(r'^(?P<course_id>\d+)/(?P<quiz_id>\d+)/upvote/$', views.upvote_solution, name='upvote_solution'),
    url(r'^(?P<course_id>\d+)/(?P<quiz_id>\d+)/delete_solution/$', views.delete_solution, name='delete_solution'),
)

quizbook/views.py
import cStringIO as StringIO
import datetime
import json
import os
import sys

from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone

from quizbook_app.forms import AuthenticateForm, UserCreateForm, NewCourseForm, NewQuizForm, UpdateQuizForm, EditQuizForm
from quizbook_app.models import Course, Quiz, QuizRecord, Quote, Preamble, Practice
from quizbook_app.power import print_terminal

def get_about(request):
    user = request.user
    context = {"user": user}
    return render(request, 'about.html', context)

quizbook/templates/course_browse.html
{% extends "base.html" %}

{% block title %}Course: {{ course.name }}{% endblock %}


{% block header%}
Course: {{ course.name }}
{% endblock %}

{% block menu %}
<li><a href="{% url 'courses:new_quiz_page' course.id %}">New</a></li>

{% if user_enrolled %}
<li><a href="{% url 'courses:practise' course.id %}">Practice</a></li>
<li><a href="{% url 'courses:drop' course.id %}">Drop</a></li>
{% else %}
<li><a href="{% url 'courses:enroll' course.id %}">Enroll</a></li>
{% endif %}

{% if user_is_creator %}
<li id="delete_button" name="delete_button"><a href="#" >Delete</a></li>
<li id="really_delete_button" name="really_delete_button"><a href="{% url 'courses:delete_course' course.id %}" >Confirm</a></li>
{% endif %}

<li class="back"><a href="{% url 'courses:index' %}">Back to Courses</a></li>

{% endblock %}


{% block body %}
	{% if error_message %}<strong>{{ error_message }}</strong>{% endif %}

	<div id="quiz_list" style="display: none">
		<!-- <h2>Quiz List<h2> -->
		{% if quizes %}
		    <ul>
		    {% for quiz in quizes %}
		        <li><a href="{{ quiz.id }}/">{{ quiz.question|truncatechars:90 }}</a></li>
		    {% endfor %}
		    </ul>
		{% else %}
		    <ul><li>No quizes are available.</li></ul>
		{% endif %}
	</div>

	<script>
		this.random_quiz = function(){
			var length = $("#random_quizes #quiz").length;
			var ran = Math.floor(Math.random()*length) + 1;
			$("#random_quizes #quiz:nth-child(" + ran + ")").fadeIn("slow");
		};

		this.reset_quizes = function(){
			$("#random_quizes #quiz").hide();
			reset_answers();
		};

		this.reveal_list = function() {
			reset_quizes();
			$("#quiz_list").fadeIn("slow");
		};
		
		$("#random_button").click(function(){
			$("#quiz_list").hide();
			reset_quizes();
  			random_quiz();
		});

		$("#quiz_list_button").click(function(){
			reveal_list();
		});

		{% for quiz in quizes %}
		$("#reveal{{ forloop.counter }}").click(function(){
			$("#reveal{{ forloop.counter }}").hide();
			$("#answer{{ forloop.counter }}").fadeIn("slow");
		});
		{% endfor %}

		this.reset_answers = function() {
			{% for quiz in quizes %}
			$("#reveal{{ forloop.counter }}").show();
			$("#answer{{ forloop.counter }}").hide();
			{% endfor %}
		};

		$("#delete_button").click(function(){
			$('#delete_button').hide();
			$('#really_delete_button').fadeIn();
			$('#really_delete_button').delay(3000).fadeOut(0, function() {
				$('#delete_button').show();
			});
			
		});

		MathJax.Hub.Register.StartupHook("End Typeset", function (message) {
			reveal_list();
		})
		
	</script>

	
{% endblock %}

quizbook/templates/course_repo.html
{% extends "base.html" %}

{% block title %}Courses{% endblock %}

{% block header%}
Courses
{% endblock %}

{% block menu %}
<li><a href="{% url 'courses:new_course_page' %}">New</a></li>
<!-- <li><a href="{% url 'courses:text_courses' %}">Text</a></li> -->
<!-- <li><a href="{% url 'courses:latex_courses' %}">Latex</a></li> -->
{% endblock %}

{% block body %}

{% if latest_course_list %}
    <ul id="course_list">
    {% for course in latest_course_list %}
        <li><a href="{% url 'courses:detail' course.id %}">{{ course.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
<ul><li>No courses are available.</ul></li>
{% endif %}
{% endblock %}

quizbook/templates/create_course.html
{% extends "base.html" %}

{% block title %}New Course{% endblock %}

{% block header%}
Create a new course
{% endblock %}

{% block menu %}
<li class="back"><a href="{% url 'courses:index' %}">Back to Courses</a></li>
{% endblock %}
{% block body %}

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	<div id="random_quizes" style="display: none;">
		<div id="quiz" style="">
			<form action="{% url 'courses:new_course_process' %}" method="post">
			{% csrf_token %}
		
				<h3>Name</h3>
				<textarea name="name" rows="1" cols="50" placeholder=""></textarea>

				<h3>Description</h3>
				<textarea name="description" rows="4" cols="50" placeholder=""></textarea>
				</br>
				<input class="css3it" type="submit" value="Submit" />
			</form>
		</div>
	</div>

	<script>

		this.reveal_answer = function() {
			$("#reveal").hide();
			$("#answer").fadeIn("slow");
		};

		$("#reveal").click(function(){
			reveal_answer();
		});

		$( document ).ready(function() {
    		{% if answer %}
    		reveal_answer();
    		{% endif %}
		});

		MathJax.Hub.Register.StartupHook("End Typeset", function (message) {
			$("#random_quizes").fadeIn("slow");
		})

		
	</script>

{% endblock %}

quizbook/templates/create_quiz.html
{% extends "base.html" %}

{% block title %}New Course{% endblock %}

{% block header%}
Create a new quiz for {{ course.name }}
{% endblock %}

{% block menu %}
<li class="back"><a href="{% url 'courses:detail' course.id %}">Back to {{ course.name }}</a></li>
{% endblock %}

{% block body %}

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	<div id="random_quizes" style="display: none;">
		<form action="{% url 'courses:new_quiz_process' course.id %}" method="post">
			{% csrf_token %}

			<h3>Question</h3>
			<textarea id="question" name="question" rows="4" cols="50" placeholder="">{{ question }}</textarea>

			<h3>Answer</h3>
			<textarea id="answer" name="answer" rows="4" cols="50" placeholder="">{{ answer }}</textarea>
			</div>

			</br>
			<input class="css3it" type="submit" value="Submit" name="_submit"/>
			<!-- <input class="css3it" type="submit" value="Preview" name="_preview"/> -->
		</form>
		<button id="preview_button" class="css3button">Preview</button>
		<button id="close_preview_button" class="css3button">Return to editing</button>
		<ul id="preview_ul"></ul>
	</div>

	<script>
		this.reveal_answer = function() {
			$("#reveal").hide();
			$("#answer").fadeIn("slow");
		};

		$("#reveal").click(function(){
			reveal_answer();
		});

		this.toggle_preview_buttons = function() {
			$( "#preview_button" ).toggle();
			$( "#close_preview_button" ).toggle();
		}

		$( "#preview_button" ).click(function() {
			var question = "<li>" + $('textarea#question').val() + "</li>";
			var answer = "<li>" + $('textarea#answer').val() + "</li>";
			toggle_preview_buttons();
			
			$( "#random_quizes" ).slideUp("slow", function() {
	    		$( "#preview_ul" ).html( question + answer );
	    		MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
	  		});
		});

		$( "#close_preview_button" ).click(function() {
			$( "#preview_ul" ).text( "" );
			toggle_preview_buttons();
			$( "#random_quizes" ).slideDown("slow");
		});

		$( document ).ready(function() {
    		{% if answer %}
    		reveal_answer();
    		{% endif %}
			$("#close_preview_button").hide();
		});

		MathJax.Hub.Register.StartupHook("End Typeset", function (message) {
			$("#random_quizes").fadeIn("slow");
		})
	</script>

{% endblock %}

quizbook/templates/create_solution.html
{% extends "base.html" %}

{% block title %}New Solution{% endblock %}

{% block header%}
Create a Solution
{% endblock %}

{% block menu %}
<li class="back"><a href="{% url 'courses:quiz_page' quiz.course.id quiz.id %}">Back</a></li>
{% endblock %}

{% block body %}

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	<div id="random_quizes" style="display: none;">
		<form action="{% url 'courses:process_add_solution' quiz.course.id quiz.id %}" method="post">
			{% csrf_token %}
			<div id="form_inside">
				<ul>
					<li id="question">{{ quiz.question }}</li>
				</ul>

				<textarea id="answer" name="answer" rows="4" cols="50" placeholder=""></textarea>

				</br>
			</div>
			<input class="css3it" type="submit" value="Submit" />
			<button id="preview_button" type="button" class="css3button">Preview</button>
			<button id="close_preview_button" type="button" class="css3button">Return to editing</button>
		</form>
		
		<ul id="preview_ul"></ul>
	</div>

	

<script>
	this.reveal_answer = function() {
		$("#reveal").hide();
		$("#answer").fadeIn("slow");
	};

	$("#reveal").click(function(){
		reveal_answer();
	});

	this.toggle_preview_buttons = function() {
		$( "#preview_button" ).toggle();
		$( "#close_preview_button" ).toggle();
	}

	$( "#preview_button" ).click(function() {
		var question = "<li>" + $('#question').html() + "</li>";
		var answer = "<li>" + $('textarea#answer').val() + "</li>";
		toggle_preview_buttons();
		
		$( "#form_inside" ).slideUp("slow", function() {
    		$( "#preview_ul" ).html( question + answer );
    		MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
  		});
	});

	$( "#close_preview_button" ).click(function() {
		$( "#preview_ul" ).text( "" );
		toggle_preview_buttons();
		$( "#form_inside" ).slideDown("slow");
	});

	$( document ).ready(function() {
		{% if answer %}
		reveal_answer();
		{% endif %}
		$("#close_preview_button").hide();
	});

	MathJax.Hub.Register.StartupHook("End Typeset", function (message) {
		$("#random_quizes").fadeIn("slow");
	})
</script>
{% endblock %}

quizbook/templates/edit_quiz.html
{% extends "base.html" %}

{% block title %}New Course{% endblock %}

{% block header%}
Edit quiz
{% endblock %}

{% block menu %}
<li class="back alert"><a href="{% url 'courses:quiz_page' quiz.course.id quiz.id %}">Cancel</a></li>
{% endblock %}

{% block body %}

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	<div id="random_quizes" style="display: none;">
		<form action="{% url 'courses:edit_quiz_process' quiz.course.id quiz.id %}" method="post">
			{% csrf_token %}

			<h3>Question</h3>
			<textarea id="question" name="question" rows="4" cols="50" placeholder="">{{ quiz.question }}</textarea>

			<h3>Answer</h3>
			<textarea id="answer" name="answer" rows="4" cols="50" placeholder="">{{ quiz.answer }}</textarea>
			</div>

			</br>
			<input class="css3it" type="submit" value="Submit" />
		</form>
		<button id="preview_button" class="css3button">Preview</button>
		<button id="close_preview_button" class="css3button">Return to editing</button>
		<ul id="preview_ul"></ul>
	</div>

	

<script>
	this.reveal_answer = function() {
		$("#reveal").hide();
		$("#answer").fadeIn("slow");
	};

	$("#reveal").click(function(){
		reveal_answer();
	});

	this.toggle_preview_buttons = function() {
		$( "#preview_button" ).toggle();
		$( "#close_preview_button" ).toggle();
	}

	$( "#preview_button" ).click(function() {
		var question = "<li>" + $('textarea#question').val() + "</li>";
		var answer = "<li>" + $('textarea#answer').val() + "</li>";
		toggle_preview_buttons();
		
		$( "#random_quizes" ).slideUp("slow", function() {
    		$( "#preview_ul" ).html( question + answer );
    		MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
  		});
	});

	$( "#close_preview_button" ).click(function() {
		$( "#preview_ul" ).text( "" );
		toggle_preview_buttons();
		$( "#random_quizes" ).slideDown("slow");
	});

	$( document ).ready(function() {
		{% if answer %}
		reveal_answer();
		{% endif %}
		$("#close_preview_button").hide();
	});

	MathJax.Hub.Register.StartupHook("End Typeset", function (message) {
		$("#random_quizes").fadeIn("slow");
	})
</script>
{% endblock %}

quizbook/templates/practice_answer.html
{% extends "base.html" %}

{% block morehead%}
<link rel="stylesheet" href="{{ STATIC_PREFIX }}/static/quiz/css/quiz_template.css" type="text/css" />
{% endblock %}

{% block title %}Course: {{ quiz.course.name }}{% endblock %}

{% block header%}
Practice session for {{ quiz.course.name }}
{% endblock %}

{% block menu %}
<li><a href="{% url 'courses:practise' quiz.course.id %}">Next</a></li>
<li><a href="#" id="delete_button" id="delete_button" name="delete_button">Delete</a></li>
<li id="really_delete_button" name="really_delete_button"><a href="{% url 'courses:delete_quiz' quiz.course.id quiz.id %}">Confirm</a></li>
<li class="back"><a href="{% url 'courses:detail' quiz.course.id %}">Back to {{ quiz.course.name }}</a></li>
{% endblock %}

{% block body %}

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	<div id="random_quizes" style="display: none;">
		<div id="quiz" style="">
			<ul>
				<li>{{ quiz.question }}</li>
			</ul>
			<div id="answer_compare">
				<div id="your_answer">
					<h2>Your Answer</h2>
					{{ answer }}
				</div>

				<div id="answer_recorded">
					<h2>Answer</h2>
					{{ quiz.answer }}
				</div>
			</div>
			<form id="gradeform" action="{% url 'courses:update_quiz' quiz.course.id quiz.id %}" method="post">
				{% csrf_token %}
				Grade: <input type="number" name="grade" rows="1" cols="50" value="{{ grade }}" min="0" max="5"></input>
				<input class="css3it" type="submit" value="Update" />
			</form>
		</div>
	</div>

	<script>

		$( document ).ready(function() {

		});

		MathJax.Hub.Register.StartupHook("End Typeset", function (message) {
			$("#random_quizes").fadeIn("slow");
		})

		$("#delete_button").click(function(){
			$('#delete_button').hide();
			$('#really_delete_button').fadeIn();
			$('#really_delete_button').delay(3000).fadeOut(0, function() {
				$('#delete_button').show();
			});
			
		});

		
	</script>

{% endblock %}

quizbook/templates/practise_question.html
{% extends "base.html" %}

{% block morehead%}
<link rel="stylesheet" href="{{ STATIC_PREFIX }}/static/quiz/css/quiz_template.css" type="text/css" />
{% endblock %}

{% block title %}Course: {{ quiz.course.name }}{% endblock %}

{% block header%}
Practice session for {{ quiz.course.name }}
{% endblock %}

{% block menu %}
<li><a href="{% url 'courses:practise' quiz.course.id %}">Next</a></li>
<li><a href="#" id="delete_button" id="delete_button" name="delete_button">Delete</a></li>
<li id="really_delete_button" name="really_delete_button"><a href="{% url 'courses:delete_quiz' quiz.course.id quiz.id %}">Confirm</a></li>
<li class="back"><a href="{% url 'courses:detail' quiz.course.id %}">Back to {{ quiz.course.name }}</a></li>
{% endblock %}

{% block body %}

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	<div id="random_quizes" style="display: none;">
		<div id="quiz" style="">
			<ul>
				<li>{{ quiz.question }}</li>
			</ul>
			<form action="{% url 'courses:answer' quiz.id %}" method="post"> {% csrf_token %}
				<textarea name="answer" rows="4" cols="50" placeholder="" style="width: 940px;"></textarea>
				</br><input type="submit" value="Submit" />
			</form>
		</div>
	</div>

	<script>

		$( document ).ready(function() {

		});

		MathJax.Hub.Register.StartupHook("End Typeset", function (message) {
			$("#random_quizes").fadeIn("slow");
		})

		$("#delete_button").click(function(){
			$('#delete_button').hide();
			$('#really_delete_button').fadeIn();
			$('#really_delete_button').delay(3000).fadeOut(0, function() {
				$('#delete_button').show();
			});
			
		});

		
	</script>

{% endblock %}

quizbook/templates/practise_quiz.html
{% extends "base.html" %}

{% block morehead%}
<link rel="stylesheet" href="{{ STATIC_PREFIX }}/static/quiz/css/quiz_template.css" type="text/css" />
{% endblock %}

{% block title %}Course: {{ quiz.course.name }}{% endblock %}

{% block header%}
Practice seesion for {{ quiz.course.name }}
{% endblock %}

{% block menu %}
<li><a href="{% url 'courses:practise' quiz.course.id %}">Next</a></li>
<li><a href="#" id="delete_button" id="delete_button" name="delete_button">Delete</a></li>
<li id="really_delete_button" name="really_delete_button"><a href="{% url 'courses:delete_quiz' quiz.course.id quiz.id %}">Confirm</a></li>
<li class="back"><a href="{% url 'courses:detail' quiz.course.id %}">Back to {{ quiz.course.name }}</a></li>
{% endblock %}

{% block body %}

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	<div id="random_quizes" style="display: none;">
		<div id="quiz" style="">
			<ul>
				<li>{{ quiz.question }}</li>
			</ul>
			{% if answer %}
			<div id="answer_compare">
				<div id="your_answer">
					<h2>Your Answer</h2>
					{{ answer }}
				</div>

				<div id="answer_recorded">
					<h2>Answer</h2>
					{{ quiz.answer }}
				</div>
			</div>
			<form id="gradeform" action="{% url 'courses:update_quiz' quiz.course.id quiz.id %}" method="post">
				{% csrf_token %}
				Grade: <input type="number" name="grade" rows="1" cols="50" value="{{ grade }}" min="0" max="100"></input>
				<input class="css3it" type="submit" value="Update" />
			</form>
			{% else %}
			<form action="{% url 'courses:answer' quiz.id %}" method="post"> {% csrf_token %}
				<textarea name="answer" rows="4" cols="50" placeholder="" style="width: 940px;"></textarea>
				</br><input type="submit" value="Submit" />
			</form>
			{% endif %}
		</div>
	</div>

	<script>

		$( document ).ready(function() {

		});

		MathJax.Hub.Register.StartupHook("End Typeset", function (message) {
			$("#random_quizes").fadeIn("slow");
		})

		$("#delete_button").click(function(){
			$('#delete_button').hide();
			$('#really_delete_button').fadeIn();
			$('#really_delete_button').delay(3000).fadeOut(0, function() {
				$('#delete_button').show();
			});
			
		});

		
	</script>

{% endblock %}

quizbook/templates/quiz_browse.html
{% extends "base.html" %}

{% block morehead%}
<link rel="stylesheet" href="{{ STATIC_URL }}css/quiz_browse.css">
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

{% endblock %}

{% block title %}Course: {{ parent_course.name }}{% endblock %}

{% block header%}
Course: {{ parent_course.name }} <br>
Creator: {{ quiz.creator }} <br>
{% if user_enrolled %}
Last recorded grade: {{ last_grade.grade }}
<div id="show_grade" class="white-link"><a href="">Show grade history</a></div>
<div id="hide_grade"><a href="">Hide grade history</a></div>
<div id="grade_history">
	<csv id="traffic">
	date,username,grade
	{% for grade in grade_list %}
	"{{  grade.created_at }}", {{  user.username }}, {{ grade.grade }},
	{% endfor %}
	</csv>
	<div id="graph">
		<chart data="#traffic"
		map-length="grade"
		scale-y-linear="0 5">
		<guide-y></guide-y>
		<repeat>
		<bar></bar>
		<annotation class="bottom">
		</annotation>
		</repeat>
		</chart>
	</div>
</div>
{% endif %}
{% endblock %}

{% block second_header %}
Creator: <span id='creator_span'></span> </br>
Rank: <span id='rank_span'></span> </br>
<div id='upvote_button' class='white-link' onclick='upvote();' data_url="{% url 'courses:upvote_solution' quiz.course.id quiz.id %}">
	<a herf=''>Upvote</a>
</div>
<div id="delete_solution_button" class='white-link' data_url="{% url 'courses:delete_solution' quiz.course.id quiz.id %}"></div>
{% endblock %}

{% block menu %}

{% if user_is_creator %}
<li><a href="{% url 'courses:edit_quiz' parent_course.id quiz.id %}">Edit</a></li>
<li id="delete_button" id="delete_button" name="delete_button"><a href="#">Delete</a></li>
<li id="really_delete_button" class="confirm_alert" name="really_delete_button"><a href="{% url 'courses:delete_quiz' parent_course.id quiz.id %}">Confirm</a></li>
{% endif %}

<li class="back"><a href="{% url 'courses:detail' quiz.course.id %}">Back to {{ quiz.course.name }}</a></li>
{% endblock %}

{% block body %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div id="random_quizes" style="display: none;">
	<div id="quiz" style="">
		<ul>
			<li>
			<p>
			{{ quiz.question }}
			</p>
			</li>
			<div id="reveal" style="display: none">
				<li>
				<a href="#">Reveal answer</a>
				</li>
			</div>
			<div id="inputPreview" >

			</div>
		</ul>
	</div>
</div>

<nav>
<span id="prev" class="cbp-fwprev">&lt;</span>
<span id="next" data_index="1" data_max="{{ max }}" data_quiz_id="{{ quiz.id }}" class="cbp-fwnext">&gt;</span>
</nav>

<script src="{{ STATIC_URL }}js/quiz_browse.js"></script>
<script src="/static/js/react/react.js"></script>
<script src="/static/js/react/JSXTransformer.js"></script>
<script src="/static/js/underscore/underscore.js"></script>
<script type="text/jsx" src="/static/js/question/add_answer_react.jsx"></script>
{% endblock %}

quizbook/templates/user_page.html
{% extends "base.html" %}

{% block title %}My Courses{% endblock %}

{% block header %}
My courses
{% endblock %}
 
{% block menu %}
<li><a href="{% url 'courses:index' %}">Courses</a></li>
{% endblock %}

{% block body %}

    {% if courses %}
        <ul id='course_list'>
            {% for course in courses %}
            <li><a href="{% url 'courses:detail' course.id %}">{{ course.name }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
    <ul><li>No courses in which enrolled.</li></ul>
    {% endif %}

{% endblock %}